main:
  - name: ğŸ  Home
    url: "/"
    weight: 10
  - name: âš’ï¸ Projects
    url: "project/"
    weight: 20
  - name: ğŸ‘¨â€ğŸ« Courses
    url: "course/"
    weight: 30
  - name: ğŸ“ƒ Publications
    url: "publication/"
    weight: 40
  - name: ğŸ’¬ Posts
    url: "post/"
    weight: 50
  - name: ğŸ“ Archives
    url: "archives/"
    weight: 60
