main:
  - name: "<div class='hvr-pulse'>ğŸ  Home</div>"
    url: "/"
    weight: 10
  - name: "<div class='hvr-pulse'>âš’ï¸ Projects</div>"
    url: "project/"
    weight: 20
  - name: "<div class='hvr-pulse'>ğŸ‘¨â€ğŸ« Courses</div>"
    url: "course/"
    weight: 30
  - name: "<div class='hvr-pulse'>ğŸ“ƒ Publications</div>"
    url: "publication/"
    weight: 40
  - name: "<div class='hvr-pulse'>ğŸ’¬ Posts</div>"
    url: "post/"
    weight: 50
  - name: "<div class='hvr-pulse'>ğŸ“ Archives</div>"
    url: "archives/"
    weight: 60
